### ISSUE TITLE
创建项目报错

### ISSUE THREAD

**Issue by jeesk** [listenzz/react-native-create-app#13]
..[$] <()>  npx react-native-create-app MyApp
CREATE new React Native Project with the following options:
  name: MyApp
  packageIdentifier: com.example.myapp
  projectDir: MyApp
  license: MIT
  
CREATE: Generating the React Native Project
yarn install v1.22.19
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.45s.
Error while creating react native project MyApp
Error: Command failed with ENOENT: pod install
spawnSync pod ENOENT
    at Object.spawnSync (node:internal/child_process:1109:20)
    at Object.spawnSync (node:child_process:803:24)
    at module.exports.sync (/home/song/.npm/_npx/604e51980bdbd6f5/node_modules/execa/index.js:174:25)
    at module.exports.commandSync (/home/song/.npm/_npx/604e51980bdbd6f5/node_modules/execa/index.js:235:15)
    at createReactNativeProject (/home/song/.npm/_npx/604e51980bdbd6f5/node_modules/react-native-create-app/lib/lib.js:50:3)
    at async Object.func (/home/song/.npm/_npx/604e51980bdbd6f5/node_modules/react-native-create-app/lib/cli-command.js:22:7)

**Comment by listenzz** [comment]
这错是 ios 的，因为没有安装 cocoapod，android 应该可以运行了。
